### ISSUE TITLE
remove svg2png dependency

### ISSUE THREAD

**Issue by quanglam2807** [akabekobeko/npm-icon-gen#120]
Is it possible to remove `svg2icon` from dependencies? I'm using `icongen` in my Electron app and because `svg2icon` relies on `phantomjs-prebuilt` (which is deprecated), it adds 50 MB to the app size.

**Comment by akabekobeko** [comment]
It depends on [svg2png](https://www.npmjs.com/package/svg2png), not `svg2icon`. This npm is required to generate transparent PNGs for various icons from SVG images.

`svg2png` uses Phantom.js for SVG processing, so finding an alternative may be difficult. However, it's a problem to depend on deprecated npm.

Consider an alternative to svg2png (with `phantomjs-prebuilt`) as `icon-gen`.

**Comment by akabekobeko** [comment]
Since this matter will be implemented in #121, close it.
