### ISSUE TITLE
Promise is resolved before the generation is finished

### ISSUE THREAD

**Issue by quanglam2807** [akabekobeko/npm-icon-gen#123]
I'm not sure if it is intended behavior, but `icon-gen` promise is resolved before the generation is finished.

```js
return icongen(buildResourcesPath, '/Users/quanglam2807/Desktop', {
  report: true,
  icns: {
    name: 'e',
    sizes,
  },
})
  .then(() => {
    const icnsFileSize = fsExtra.statSync(path.join(buildResourcesPath, 'icon.icns')).size;
    console.log(icnsFileSize) // output 0
    return null;
  });
```

My project requires me to copy the generated ICNS elsewhere and because it's not ready when the promise is resolved, it corrupts the whole thing. Am I doing everything right?

**Comment by quanglam2807** [comment]
I just some tests with PR https://github.com/akabekobeko/npm-icon-gen/pull/124. It seems like this only affects ICNS generation, not ICO.

**Comment by quanglam2807** [comment]
I've fixed it. The bug occurs because the promise doesn't wait for `fs.WriteStream` to finish. This affects both `v2.0.0` and `v2.1.0`

**Comment by akabekobeko** [comment]
It will be fixed by PR merge, so close it.
