### ISSUE TITLE
v2.1.0 is not on npm

### ISSUE THREAD

**Issue by quanglam2807** [akabekobeko/npm-icon-gen#125]
v2.1.0 is not on npm. It seems like the code is already in `master` branch with changelog

**Comment by akabekobeko** [comment]
I forgot to publish. I want to incorporate PR, so I will release it again.

**Comment by akabekobeko** [comment]
I left it because of the busy work and the big changes due to the TypeScript migration of the implementation, but I will resume development.

**Comment by akabekobeko** [comment]
This issue will be closed to manage the release again with #129.
