### ISSUE TITLE
Incomplete format of the ICO file with "@icon変換"

### ISSUE THREAD

**Issue by akabekobeko** [akabekobeko/npm-icon-gen#19]
Opening an error the generated ICO files in the following applications.
- [@icon変換](http://www.towofu.net/soft/aicon.php)

**Comment by quanglam2807** [comment]
+1

**Comment by quanglam2807** [comment]
@akabekobeko You can take a look at: https://github.com/steambap/png-to-ico. It works for me.

**Comment by akabekobeko** [comment]
@quanglam2807 

Thank you. I will refer to it.

**Comment by akabekobeko** [comment]
The ico file created by `png-to-icon` also got the same error.

![ss](https://cloud.githubusercontent.com/assets/1257526/24782006/769e9726-1b7e-11e7-827c-f6e14e560240.png)

**Comment by quanglam2807** [comment]
@akabekobeko What do you use to test it? I used that library with my project and at least, it generates icons readable by Windows.

https://github.com/webcatalog/webcatalog/blob/master/src/ui/store/helpers/installAppAsync.js#L33

**Comment by akabekobeko** [comment]
Both the icon-gen and the icon created by png-to-ico are working normally on Windows.

However, reading with [@icon変換](http://www.towofu.net/soft/aicon.php) will result in an error. Although it may be a problem of `@icon変換`, `@icon変換` is commonly used in Japanese Windows environment and I want to fix it.

Nonetheless, Z is not OSS and error information is scarce so investigation is difficult.

**Comment by akabekobeko** [comment]
I changed the title as it might be a problem unique to the application.

**Comment by akabekobeko** [comment]
Since we have been left untouched for a long time, we close this issue.
