### ISSUE TITLE
ICNS size adjustments

### ISSUE THREAD

**Issue by atdrago** [akabekobeko/npm-icon-gen#32]
First, let me say **thank you for this utility!!** I needed a way to generate both `.ico` and `.icns` icons cross-platform, without special platform-dependent programs, and this utility is great! 💯 

Now to the issue 😬

From [Apple's documentation](https://developer.apple.com/library/mac/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html) on `.icns` file creation: 
> A complete set consists of the following:
```
> icon_16x16.png
> icon_16x16@2x.png
> icon_32x32.png
> icon_32x32@2x.png
> icon_128x128.png
> icon_128x128@2x.png
> icon_256x256.png
> icon_256x256@2x.png
> icon_512x512.png
> icon_512x512@2x.png
```

From your documentation (and reading the code), I see two potential discrepancies. Please let me know if I'm wrong.
1. You *do not* require a `16.png` (16x16) image, which Apple recommends.
2. ~~You *do* require a `64.png` (64x64) image, which Apple does not require.~~ *See correction in my next comment*

What are your thoughts? And is fixing this just as simple as editing [the array here](https://github.com/akabekobeko/npm-icon-gen/blob/master/src/lib/icns-generator.js#L30-L39)?

Thank you!

**Comment by atdrago** [comment]
**Correction:** `64.png` should stay, as it should be used for the 32x32 retina image (as you have it now).

**Comment by akabekobeko** [comment]
memo: [Apple Icon Image format - Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Apple_Icon_Image_format)

**Comment by akabekobeko** [comment]
@atdrago 

Support an `ipc4` - `ipc6`, `16.png` is stored as `ipc4`.
Please check with `v1.0.3`.

**Comment by atdrago** [comment]
Verified I now see 11 icons at the correct dimensions in the generated ICNS file.
Thank you!
👍
