### ISSUE TITLE
Allow specifying icon file name

### ISSUE THREAD

**Issue by atdrago** [akabekobeko/npm-icon-gen#38]
Currently, icons get saved to a directory as either "app.icns", "app.ico", or "favicon.ico". It makes sense to default the favicon to "favicon.ico", but users may want to use a name other than "app.icns" or "app.ico" for their application's icon. It would be nice to be able to specify the name of the saved icon file. My current workaround is to let the file write out as "app.ext" to a temp directory, then rename/move it using the user's preferred file name.

Relevant code block:
https://github.com/akabekobeko/npm-icon-gen/blob/master/src/lib/icon-generator.js#L123-L141

One possible implementation would be to add an object property to `options`. Something like:
```js
icongen('./images', './dist', {
    modes: ['icns', 'ico'],
    names: { 'icns': 'my-icon' } // The ico file would default to "app"
});
```

**Comment by akabekobeko** [comment]
@atdrago

Support change a file names of the **ICO** and **ICNS**.
Please check with `v1.0.4`.

**Comment by atdrago** [comment]
👍 Thank you!
