### ISSUE TITLE
Icns not working

### ISSUE THREAD

**Issue by mifi** [akabekobeko/npm-icon-gen#42]
Great project!
I tried generating the sample.svg from test using
icon-gen -i sample.svg -m icns -o ./icon-dist -r
The icns file itself shows the icon in Finder, and I can open it in preview and see the sizes there, however when I try to apply it to a folder (or electron app) the icon doesn't show up.
node v 6.7.0, mac os sierra.
I attached generated icon.

Icon generetor from SVG:
  src: /Users/mifi/Desktop/icon-test/sample.svg
  dir: /Users/mifi/Desktop/icon-test/icon-dist
SVG to PNG:
  Create: /var/folders/fv/s06vd5bd28n2ymghb4k7gq140000gn/T/ba757b91-be2e-41a5-970c-489d32b621ed/16.png
  Create: /var/folders/fv/s06vd5bd28n2ymghb4k7gq140000gn/T/ba757b91-be2e-41a5-970c-489d32b621ed/32.png
  Create: /var/folders/fv/s06vd5bd28n2ymghb4k7gq140000gn/T/ba757b91-be2e-41a5-970c-489d32b621ed/64.png
  Create: /var/folders/fv/s06vd5bd28n2ymghb4k7gq140000gn/T/ba757b91-be2e-41a5-970c-489d32b621ed/128.png
  Create: /var/folders/fv/s06vd5bd28n2ymghb4k7gq140000gn/T/ba757b91-be2e-41a5-970c-489d32b621ed/256.png
  Create: /var/folders/fv/s06vd5bd28n2ymghb4k7gq140000gn/T/ba757b91-be2e-41a5-970c-489d32b621ed/512.png
  Create: /var/folders/fv/s06vd5bd28n2ymghb4k7gq140000gn/T/ba757b91-be2e-41a5-970c-489d32b621ed/1024.png
ICNS:
  Create: /Users/mifi/Desktop/icon-test/icon-dist/app.icns

[app.icns.zip](https://github.com/akabekobeko/npm-icon-gen/files/572431/app.icns.zip)

**Comment by akabekobeko** [comment]
The icon we tried to preview it in my environment, but it seems normal.

**My environment:**

* MacBook Pro (Retina, 15-inch, Early 2013)
* macOS Sierra v10.12.1

Could you put a screenshot (Finder, Preview, or etc) so I want to see the broken state?

**Comment by mifi** [comment]
The icon I attached it working for you?
I have Mac OS Sierra 10.12 on MacBook Pro (Retina, 13-inch, Mid 2014)

Here's a video where I try to apply the Icon to a new folder in Finder (Get Info):
https://gfycat.com/MerryDirtyAfricangroundhornbill

With my fix (#43) it's working and the icon of the folder changes.

**Comment by akabekobeko** [comment]
Thank you.
I understood the summary problem.

I was seeing was a display on the `Preview.app`.
Check the Pull request because I can see the problem.
