### ISSUE TITLE
ICNS displays incorrectly in Launchpad folder

### ISSUE THREAD

**Issue by quanglam2807** [akabekobeko/npm-icon-gen#53]
webcatalog/webcatalog#94

I tried to add Retina icon types but it didn't play well. #52

**Comment by akabekobeko** [comment]
There may be problems with Retina. I will fix it in #54.

**Comment by quanglam2807** [comment]
@akabekobeko Have you checkedhttps://github.com/pornel/libicns/blob/64ac8719fcf43dde9d923304b744d972c760b4eb/src/icns.h#L96

**Comment by akabekobeko** [comment]
@quanglam2807 

I checked it at [Apple Icon Image format](https://en.wikipedia.org/wiki/Apple_Icon_Image_format).

It seems that `ICNS_256x256_2X_32BIT_ARGB_DATA` of libicns is `256 * 2 = 512`, but specifying 512 as `ic14` with icon-gen failed to specify folder properly.

However, `libicns` seems more accurate as information, so I will refer to the implementation.
