### ISSUE TITLE
Icons generation does not complete

### ISSUE THREAD

**Issue by navenedrob** [akabekobeko/npm-icon-gen#79]
Tried with the following config using (node 8.9.1, npm 5.5.1):

icon-gen -i ./public/meta/icon.png -o ./public/meta -m icns,ico

```
(node:3825) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10):

 Error: TypeError: null is not an object (evaluating 'el.setAttribute')

  undefined:6
  :16
TypeError: null is not an object (evaluating 'el.getAttribute')

  undefined:6
  :27
Width or height could not be determined from either the source file or the supplied dimension
s

  phantomjs://code/converter.js:49 in onLoadFinished
(node:3825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the
 future, promise rejections that are not handled will terminate the Node.js process with a no
n-zero exit code.
```

**Comment by akabekobeko** [comment]
In my environment the problem did not reproduce.

* OS : macOS High Sierra
* Node: 8.9.1
* npm: 5.5.1

I released icon-gen v1.2.0. This may fix the problem. If the problem seems to be reproduced please comment again.

**Comment by navenedrob** [comment]
@akabekobeko I will do another test today and see if I can reproduce it. My icon source image had a lot of transparency and I'm wondering if the issue is/was tied to that fact?

> Width or height could not be determined

**Comment by akabekobeko** [comment]
The command you executed is

```
icon-gen -i ./public/meta/icon.png -o ./public/meta -m icns,ico
```

, But if you do not specify the -t option, **SVG** will be covered. If you want to create an icon from **PNG**

```
icon-gen -i ./public/meta -o ./public/meta -m icns,ico -t png
```

Please set a folder path that contains the -t option and the PNG file as, The PNG size and file name required for the icon are described in the README.
