### ISSUE TITLE
Use pngjs-nozlib instead of pngjs.

### ISSUE THREAD

**Issue by akabekobeko** [akabekobeko/npm-icon-gen#87]
According to comments on [this issue](https://github.com/lukeapage/pngjs/issues/105) pngjs is not actively maintained. Therefore, use [pngjs-nozlib](https://www.npmjs.com/package/pngjs-nozlib).

**Comment by akabekobeko** [comment]
Relation: #82

**Comment by DionDavid** [comment]
And how can I switch from pngjs to pngjs-nozlib? It is required inside your library.

**Comment by DionDavid** [comment]
Thank you! When are you planning to publish version 1.2.1 for production?

**Comment by akabekobeko** [comment]
@DionDavid 
Yes. It supports with v1.2.1.
