### ISSUE TITLE
PNG sizes

### ISSUE THREAD

**Issue by krumpak** [akabekobeko/npm-icon-gen#93]
is it possible to set sizes for PNGs like "favicon=[24,64]"?

**Comment by krumpak** [comment]
Thank you for the answer. Have you considered implementing the same feature for PNGs as it is for ICO/ICNS in the future?

**Comment by akabekobeko** [comment]
@krumpak I also needed the size designation of PNG. Receive your proposal favicon responds with PNG size specification or new mode.
