### ISSUE TITLE
How to keep the individual png size files?

### ISSUE THREAD

**Issue by AoDev** [akabekobeko/npm-icon-gen#96]
I am building an app with Electron. For Linux, I would need all the png's generated.
Is there a way to do this with icon-gen?

I can see that it writes individual sized png's to a temp directory with `-r options`.
I just need to be able to keep and tell where to put these.

Is this possible? Maybe it's a feature request?

**Comment by akabekobeko** [comment]
Sorry for the late reply.

I found that you need an icon that is not currently supported for `apple-touch-icon` or `manifest.json` in PWA.

Therefore we plan to add a new mode (#97) to generate PNG of the specified size. We support this issue in a new mode.
